//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stone.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stone.Framework.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo {0} deve ser preenchido.
        /// </summary>
        public static string CampoXdeveSerPreenchido {
            get {
                return ResourceManager.GetString("CampoXdeveSerPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não autenticado.
        /// </summary>
        public static string ClienteNaoAutenticado {
            get {
                return ResourceManager.GetString("ClienteNaoAutenticado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de validade do cartão inválido.
        /// </summary>
        public static string DataDeValidadeCartaoInvalido {
            get {
                return ResourceManager.GetString("DataDeValidadeCartaoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha de autenticação do cliente.
        /// </summary>
        public static string FalhaDeAutenticacaoDoCliente {
            get {
                return ResourceManager.GetString("FalhaDeAutenticacaoDoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de cartão inválido.
        /// </summary>
        public static string NumeroDeCartaoInvalido {
            get {
                return ResourceManager.GetString("NumeroDeCartaoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro atualizado com sucesso.
        /// </summary>
        public static string RegistroAtualizadoComSucesso {
            get {
                return ResourceManager.GetString("RegistroAtualizadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro cadastrado com sucesso.
        /// </summary>
        public static string RegistroCadastradoComSucesso {
            get {
                return ResourceManager.GetString("RegistroCadastradoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro excluído com sucesso.
        /// </summary>
        public static string RegistroExcluidoComSucesso {
            get {
                return ResourceManager.GetString("RegistroExcluidoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não localizado.
        /// </summary>
        public static string RegistroNaoLocalizado {
            get {
                return ResourceManager.GetString("RegistroNaoLocalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve ter entre 4 e 6 dítigos.
        /// </summary>
        public static string SenhaDeveTerEntre4a6digitos {
            get {
                return ResourceManager.GetString("SenhaDeveTerEntre4a6digitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação aprovada.
        /// </summary>
        public static string TransacaoAprovada {
            get {
                return ResourceManager.GetString("TransacaoAprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação cadastrada com sucesso.
        /// </summary>
        public static string TransacaoCadastradaComSucesso {
            get {
                return ResourceManager.GetString("TransacaoCadastradaComSucesso", resourceCulture);
            }
        }
    }
}
